### ISSUE TITLE
JSON::ParserErrorでSyncDocbaseJobでの移行が失敗する

### ISSUE THREAD

**Issue by dak2** [sentium/docbase_to_kibela#2]
## 概要

SyncDocbaseJobでの記事移行時に `JSON::ParserError` でJOBがこけてしまう。
下記はその際のログ

```
rails-server_1   | 05:49:07 web.1    | 2022-07-31T05:49:07.482Z pid=7 tid=9cv class=SyncDocbaseJob jid=660cc25f55f5ab01ff840f7e INFO: start
rails-server_1   | 05:49:08 web.1    | 2022-07-31T05:49:08.064Z pid=7 tid=9cv class=SyncDocbaseJob jid=660cc25f55f5ab01ff840f7e INFO: Adding dead SyncDocbaseJob job 660cc25f55f5ab01ff840f7e
rails-server_1   | 05:49:08 web.1    | 2022-07-31T05:49:08.067Z pid=7 tid=9cv class=SyncDocbaseJob jid=660cc25f55f5ab01ff840f7e elapsed=0.585 INFO: fail
rails-server_1   | 05:49:08 web.1    | 2022-07-31T05:49:08.068Z pid=7 tid=9cv WARN: {"context":"Job raised exception","job":{"retry":3,"queue":"default","class":"SyncDocbaseJob","args":["2018/12/24","https://api.docbase.io/teams/starx/posts?page=101&per_page=100&q=changed_at%3A2018-12-24~%2A+asc%3Achanged_at"],"jid":"660cc25f55f5ab01ff840f7e","created_at":1659246389.3371916,"enqueued_at":1659246547.48161,"error_message":"809: unexpected token at 'Internal Server Error\nIf you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.'","error_class":"JSON::ParserError","failed_at":1659246392.628953,"retry_count":2,"retried_at":1659246479.87379},"jobstr":"{\"retry\":3,\"queue\":\"default\",\"class\":\"SyncDocbaseJob\",\"args\":[\"2018/12/24\",\"https://api.docbase.io/teams/starx/posts?page=101&per_page=100&q=changed_at%3A2018-12-24~%2A+asc%3Achanged_at\"],\"jid\":\"660cc25f55f5ab01ff840f7e\",\"created_at\":1659246389.3371916,\"enqueued_at\":1659246547.48161,\"error_message\":\"809: unexpected token at 'Internal Server Error\\nIf you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.'\",\"error_class\":\"JSON::ParserError\",\"failed_at\":1659246392.628953,\"retry_count\":2,\"retried_at\":1659246479.87379}"}
rails-server_1   | 05:49:08 web.1    | 2022-07-31T05:49:08.068Z pid=7 tid=9cv WARN: JSON::ParserError: 809: unexpected token at 'Internal Server Error
rails-server_1   | 05:49:08 web.1    | If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.'
rails-server_1   | 05:49:08 web.1    | 2022-07-31T05:49:08.068Z pid=7 tid=9cv WARN: /usr/local/lib/ruby/3.0.0/json/common.rb:216:in `parse'
rails-server_1   | 05:49:08 web.1    | /usr/local/lib/ruby/3.0.0/json/common.rb:216:in `parse'
rails-server_1   | 05:49:08 web.1    | /app/app/models/concerns/docbase/base_module.rb:74:in `get'
rails-server_1   | 05:49:08 web.1    | /app/app/models/concerns/docbase/base_module.rb:112:in `posts'
rails-server_1   | 05:49:08 web.1    | /app/app/models/post.rb:38:in `sync_by_docbase'
rails-server_1   | 05:49:08 web.1    | /app/app/jobs/sync_docbase_job.rb:10:in `perform'
```

## 調査したこと

下記でリクエストしたところ、Internal Server Errorがレスポンスとして返って来た。
それをParseしてこけていることを確認。
リクエスト制限か何かで引っ掛かっていそう

```shell
curl --location --request GET 'https://api.docbase.io/teams/starx/posts?page=101&per_page=100&q=changed_at%3A2018-12-24~%2A+asc%3Achanged_at' \
--header 'X-DocBaseToken: ******************' \
--header 'Content-Type: application/json'
```

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

## 対応方針
一度全て移行してから抜けている部分をimportする

**Comment by dak2** [comment]
### 今ローカルに保存された記事数

```
irb(main):006:0> Post.all.pluck(:origin_url).uniq.size
   (14.4ms)  SELECT "posts"."origin_url" FROM "posts"
=> 13491
```

### docbaseの記事数

`created_at:*~2022-08-05` だと13514件

<img width="900" alt="スクリーンショット 2022-08-05 9 13 14" src="https://user-images.githubusercontent.com/32436625/182975863-fc40beb9-9920-4fda-802f-cc8c6ecf964c.png">

`changed_at:*~2022-08-05` だと13401件

<img width="926" alt="スクリーンショット 2022-08-05 9 13 31" src="https://user-images.githubusercontent.com/32436625/182975879-742cc72c-0b42-4abf-a9fa-e22a91b72eae.png">

どっちが正なのか...？

**Comment by dak2** [comment]
## 結論
13491でOK

```
irb(main):001:0> Post.all.size
   (6.9ms)  SELECT COUNT(*) FROM "posts"
=> 13491
```

### changed_at:2017-01-01\~\* で検索した結果: 13516

```shell
# https://api.docbase.io/teams/starx/posts\?q\=changed_at:2017-01-01\~\*
  "meta": {
    "previous_page": null,
    "next_page": "https://api.docbase.io/teams/starx/posts?page=2&per_page=20&q=changed_at%3A2017-01-01~%2A",
    "total": 13516
  }
```

### changed_at:2017-01-01\~\*%20is:draft で検索した結果: 23

```shell
# https://api.docbase.io/teams/starx/posts\?q\=changed_at:2017-01-01\~\*%20is:draft
  "meta": {
    "previous_page": null,
    "next_page": "https://api.docbase.io/teams/starx/posts?page=2&per_page=20&q=changed_at%3A2017-01-01~%2A+is%3Adraft",
    "total": 23
  }
```

### まとめ
13516 - 23 = 13493 - 2(https://starx.docbase.io/posts/608164, https://starx.docbase.io/posts/608165) = 13491

```
irb(main):003:0> Post.where(origin_url: ['https://starx.docbase.io/posts/608164', 'https://starx.docbase.io/pos
ts/608165']).size
   (9.4ms)  SELECT COUNT(*) FROM "posts" WHERE "posts"."origin_url" IN ($1, $2)  [["origin_url", "https://starx.docbase.io/posts/608164"], ["origin_url", "https://starx.docbase.io/posts/608165"]]
=> 0
```
